### ISSUE TITLE
[Feature] Just little but nice fix

### ISSUE THREAD

**Issue by CassieAinsworth** [5oundtech/WoblaExplorer#1]
Hello!
Usign as administrator option has been noticed that item "run as admin" can be reselected. I think you need to remove the possibility of selecting this mode, if I am already in it

**Comment by 5oundtech** [comment]
I'll try to release these feature as fast as i can;)

**Comment by 5oundtech** [comment]
@CassieAinsworth, Now it is fixed with one property and trigger with binding;

**Comment by CassieAinsworth** [comment]
@5oundtech, Yet, now it is working allrigth!
